services:
  web:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE:${NEXT_PUBLIC_ENV_VARIABLE}
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "3000:3000"
    networks:
      - my_network

# resolve container_name as hostname
networks:
  my_network:
    name: my_network
    external: true
